In [233]:
# INSTALL THE REQUIRED LIBRARIES
! pip install pyodbc

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyodbc in c:\users\manchala govardhan\appdata\roaming\python\python314\site-packages (5.3.0)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [234]:
! pip install unidecode

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: unidecode in c:\users\manchala govardhan\appdata\roaming\python\python314\site-packages (1.4.0)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [235]:
import numpy as np
import pandas as pd
import pyodbc
from unidecode import unidecode

In [236]:

server="GOVARDHAN\SQLEXPRESS"
database="live_project"

connection_string=(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    f"SERVER={server};"
    f"DATABASE={database};"
    "Trusted_Connection=yes;"
)

conn = pyodbc.connect(connection_string)

<>:1: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
<>:1: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
C:\Users\Manchala Govardhan\AppData\Local\Temp\ipykernel_14452\2392609193.py:1: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
  server="GOVARDHAN\SQLEXPRESS"

In [237]:
query="select * from olist_customers_dataset"
customers= pd.read_sql(query, conn)

C:\Users\Manchala Govardhan\AppData\Local\Temp\ipykernel_14452\1667547915.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers= pd.read_sql(query, conn)

In [238]:
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00012a2ce6f8dcda20d059ce98491703,248ffe10d632bebe4f7267f1f44844c9,6273,osasco,SP
1,000161a058600d5901f007fab4c27140,b0015e09bb4b6e47c52844fab5fb6638,35550,itapecerica,MG
2,0001fd6190edaaf884bcaf3d49edf079,94b11d37cd61cb2994a194d11f89682b,29830,nova venecia,ES
3,0002414f95344307404f0ace7a26f1d5,4893ad4ea28b2c5b3ddf4e82e79db9e6,39664,mendonca,MG
4,000379cdec625522490c315e70c7a9fb,0b83f73b19c2019e182fd552c048a22c,4841,sao paulo,SP
...,...,...,...,...,...
99436,fffecc9f79fd8c764f843e9951b11341,e5794df8573fa179a90a7b797fc4b71f,95630,parobe,RS
99437,fffeda5b6d849fbd39689bb92087f431,afbb5a642107cf6bb1ca68e863175f03,22461,rio de janeiro,RJ
99438,ffff42319e9b2d713724ae527742af25,680213db6ebd9e4f24d03280cbe10346,6754,taboao da serra,SP
99439,ffffa3172527f765de70084a7e53aae8,48fd7dec70f2b104a1d5e8c5c639102b,37130,alfenas,MG
99440,ffffe8b65bbe3087b653a978c870db99,736e6bfa0510aa5b878881a226a5fd89,6172,osasco,SP

In [239]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [240]:
customers.sample(10)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
78474,c95b27f706ec07cd720330a9116df8b9,d524e6d0027c6e4f03e9969e2613f1dd,30180,belo horizonte,MG
23903,3d844101c1139f3f062e266bb772b529,50c6a0339f3b3ec022e753b7a67fc418,59067,natal,RN
21492,373bf4e0ff53138b7b90d527fbfc095e,dab42470534eadccc6e18c8bc9ae4b4d,23515,rio de janeiro,RJ
89422,e5cede01799d43206f0e40fcfe683457,59f5e5c0ff8a1ca7026faa8c316693eb,17900,dracena,SP
13405,22705c3b9d99040b971bd4aeb236ecdc,f38c2ba31f000079afd5a0416d37eea6,95590,tramandai,RS
17581,2d5961372f483e6ca5478477d3289a14,37ffc4529f4914b4d8fa628ccf1a422b,29600,afonso claudio,ES
40308,68451b39b1314302c08c65a29f1140fc,781ae350edb16842380e81d7c7feb431,20740,rio de janeiro,RJ
93838,f120f070594b950c2921147b0914a8f7,a43a63741cbbc48056838d0bcf198ee4,88067,florianopolis,SC
95908,f6b4f8d8ec46e8a2eef187ce2073cbb7,d97fe0933e8ef1857700de4ac047dc89,72235,brasilia,DF
12935,214bfa16b119c00cf6883e976038c1a5,b47715fad5cbc17bfb21e9ab646fdfb2,15140,balsamo,SP

In [241]:
# capitalizing first alphabet of each word for city.
customers["customer_city"]= customers["customer_city"].str.title()

In [242]:
customers["customer_id"].nunique()

99441

In [243]:
customers["customer_unique_id"].nunique()

96096

In [244]:
sum(customers["customer_id"]==customers["customer_unique_id"])

0

In [245]:
query="select * from olist_geolocation_dataset"
geo= pd.read_sql(query, conn)

C:\Users\Manchala Govardhan\AppData\Local\Temp\ipykernel_14452\3619535398.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  geo= pd.read_sql(query, conn)

In [246]:
geo

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,01037,-23.545622,-46.639294,sao paulo,SP
1,01046,-23.546082,-46.644821,sao paulo,SP
2,01046,-23.546129,-46.642952,sao paulo,SP
3,01041,-23.544392,-46.639500,sao paulo,SP
4,01035,-23.541578,-46.641605,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068640,-52.010704,tapejara,RS
1000159,99900,-27.877125,-52.224884,getulio vargas,RS
1000160,99950,-28.071856,-52.014717,tapejara,RS
1000161,99980,-28.388931,-51.846870,david canabarro,RS
1000162,99950,-28.070103,-52.018658,tapejara,RS

In [247]:
geo["geolocation_city"]= geo["geolocation_city"].str.title()

In [248]:
geo.duplicated().sum()

np.int64(262154)

In [249]:
geo.drop_duplicates(inplace=True)

In [250]:
geo.shape

(738009, 5)

In [251]:
# drop latitude and longitude column
geo.drop(columns=["geolocation_lat","geolocation_lng"], inplace=True)

In [252]:
geo

        geolocation_zip_code_prefix geolocation_city geolocation_state
0                             01037        Sao Paulo                SP
1                             01046        Sao Paulo                SP
2                             01046        Sao Paulo                SP
3                             01041        Sao Paulo                SP
4                             01035        Sao Paulo                SP
...                             ...              ...               ...
1000155                       99965       Agua Santa                RS
1000156                       99950         Tapejara                RS
1000157                       99950         Tapejara                RS
1000158                       99950         Tapejara                RS
1000161                       99980  David Canabarro                RS

[738009 rows x 3 columns]

In [253]:
geo["geolocation_city"].sample(10)

583177                            Caete
890099                         Santa Fe
813678                      Porto Velho
590119                        Caratinga
742279                        Fortaleza
959800                         Gravatai
139121                        Sao Paulo
488603    Sao Jose Do Vale Do Rio Preto
735028                            Natal
705589                          Aracaju
Name: geolocation_city, dtype: object

In [254]:
print(geo["geolocation_city"].nunique())

8011

In [255]:
geo["geolocation_city"]= geo["geolocation_city"].apply(lambda x: unidecode(x))

In [256]:
print(geo["geolocation_city"].nunique())

5969

In [257]:
def contains_number(s):
    return any(i.isdigit() for i in  str(s))

In [258]:
geo[geo["geolocation_city"].apply(contains_number)]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
377210,17970,Sao Joao Do Pau D%26Apos%3Balho,SP
538905,29735,Quilometro 14 Do Mutum,ES
539470,29735,Quilometro 14 Do Mutum,ES
726758,57010,Maceia3,AL
786179,71880,Riacho Fundo 2,DF
823386,78278,Lambari D%26Apos%3Boeste,MT
896733,87365,4O. Centenario,PR
896977,87365,4o Centenario,PR
897217,87365,4o Centenario,PR
977775,96130,Colonia Z-3,RS
977787,96130,Colonia Z-3,RS
977813,96130,Colonia Z-3,RS

In [259]:
import re

def remove_numbers(s):
    return re.sub(r'\d+','', str(s))

In [260]:
geo["geolocation_city"]= geo["geolocation_city"].apply(remove_numbers)

In [261]:
geo[geo["geolocation_city"].apply(contains_number)]

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_city, geolocation_state]
Index: []

In [262]:
geo[geo["geolocation_zip_code_prefix"]=="17970"]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
376805,17970,Sao Joao Do Pau D'Alho,SP
376827,17970,Sao Joao Do Pau D'Alho,SP
376905,17970,Sao Joao Do Pau D'Alho,SP
376937,17970,Sao Joao Do Pau D Alho,SP
377022,17970,Sao Joao Do Pau D Alho,SP
377073,17970,Sao Joao Do Pau D'Alho,SP
377082,17970,Sao Joao Do Pau D'Alho,SP
377092,17970,Sao Joao Do Pau Dalho,SP
377138,17970,Sao Joao Do Pau D'Alho,SP
377186,17970,Sao Joao Do Pau Dalho,SP
377210,17970,Sao Joao Do Pau D%Apos%Balho,SP
377306,17970,Sao Joao Do Pau D Alho,SP
377324,17970,Sao Joao Do Pau D'Alho,SP
377331,17970,Sao Joao Do Pau D'Alho,SP
377496,17970,Sao Joao Do Pau D'Alho,SP

In [263]:
geo["geolocation_city"]= geo["geolocation_city"].str.replace("'","",regex=False)

In [264]:
geo[geo["geolocation_zip_code_prefix"]=="17970"]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
376805,17970,Sao Joao Do Pau DAlho,SP
376827,17970,Sao Joao Do Pau DAlho,SP
376905,17970,Sao Joao Do Pau DAlho,SP
376937,17970,Sao Joao Do Pau D Alho,SP
377022,17970,Sao Joao Do Pau D Alho,SP
377073,17970,Sao Joao Do Pau DAlho,SP
377082,17970,Sao Joao Do Pau DAlho,SP
377092,17970,Sao Joao Do Pau Dalho,SP
377138,17970,Sao Joao Do Pau DAlho,SP
377186,17970,Sao Joao Do Pau Dalho,SP
377210,17970,Sao Joao Do Pau D%Apos%Balho,SP
377306,17970,Sao Joao Do Pau D Alho,SP
377324,17970,Sao Joao Do Pau DAlho,SP
377331,17970,Sao Joao Do Pau DAlho,SP
377496,17970,Sao Joao Do Pau DAlho,SP

In [265]:
geo.duplicated().sum()

np.int64(718393)

In [266]:
geo.shape

(738009, 3)

In [267]:
geo[geo["geolocation_city"].str.contains("'", na=False)]

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_city, geolocation_state]
Index: []

In [268]:
geo[geo["geolocation_city"].str.startswith("*")]

       geolocation_zip_code_prefix geolocation_city geolocation_state
851430                       81470         * Cidade                PR

In [269]:
geo["geolocation_city"]= geo["geolocation_city"].str.replace("*","", regex=False)

In [270]:
geo[geo["geolocation_city"].str.startswith("...")]

       geolocation_zip_code_prefix    geolocation_city geolocation_state
525385                       28930  ...Arraial Do Cabo                RJ

In [271]:
geo["geolocation_city"]= geo["geolocation_city"].str.replace("...",'', regex=False)

In [272]:
geo[geo["geolocation_city"].str.startswith("...")]

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_city, geolocation_state]
Index: []

In [273]:
geo["geolocation_city"].nunique()

5966

In [274]:
geo[geo["geolocation_zip_code_prefix"]=="17970"]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
376805,17970,Sao Joao Do Pau DAlho,SP
376827,17970,Sao Joao Do Pau DAlho,SP
376905,17970,Sao Joao Do Pau DAlho,SP
376937,17970,Sao Joao Do Pau D Alho,SP
377022,17970,Sao Joao Do Pau D Alho,SP
377073,17970,Sao Joao Do Pau DAlho,SP
377082,17970,Sao Joao Do Pau DAlho,SP
377092,17970,Sao Joao Do Pau Dalho,SP
377138,17970,Sao Joao Do Pau DAlho,SP
377186,17970,Sao Joao Do Pau Dalho,SP
377210,17970,Sao Joao Do Pau D%Apos%Balho,SP
377306,17970,Sao Joao Do Pau D Alho,SP
377324,17970,Sao Joao Do Pau DAlho,SP
377331,17970,Sao Joao Do Pau DAlho,SP
377496,17970,Sao Joao Do Pau DAlho,SP

In [275]:
def keep_only_text(x):
    if pd.isna(x):
        return x
    # remove everything except alphabets and spaces
    return re.sub(r"[^A-Za-z\s]", "", str(x)).strip()

In [276]:
geo["geolocation_city"]= geo["geolocation_city"].apply(keep_only_text)

In [277]:
geo["geolocation_city"]

0                Sao Paulo
1                Sao Paulo
2                Sao Paulo
3                Sao Paulo
4                Sao Paulo
                ...
1000155         Agua Santa
1000156           Tapejara
1000157           Tapejara
1000158           Tapejara
1000161    David Canabarro
Name: geolocation_city, Length: 738009, dtype: object

In [278]:
geo[geo["geolocation_zip_code_prefix"]=="17970"]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
376805,17970,Sao Joao Do Pau DAlho,SP
376827,17970,Sao Joao Do Pau DAlho,SP
376905,17970,Sao Joao Do Pau DAlho,SP
376937,17970,Sao Joao Do Pau D Alho,SP
377022,17970,Sao Joao Do Pau D Alho,SP
377073,17970,Sao Joao Do Pau DAlho,SP
377082,17970,Sao Joao Do Pau DAlho,SP
377092,17970,Sao Joao Do Pau Dalho,SP
377138,17970,Sao Joao Do Pau DAlho,SP
377186,17970,Sao Joao Do Pau Dalho,SP
377210,17970,Sao Joao Do Pau DAposBalho,SP
377306,17970,Sao Joao Do Pau D Alho,SP
377324,17970,Sao Joao Do Pau DAlho,SP
377331,17970,Sao Joao Do Pau DAlho,SP
377496,17970,Sao Joao Do Pau DAlho,SP

In [279]:
geo["geolocation_city"]= geo["geolocation_city"].str.replace("Sao Joao Do Pau D Alho","Sao Joao Do Pau DAlho")

In [280]:
geo[geo["geolocation_zip_code_prefix"]=="17970"]

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
376805,17970,Sao Joao Do Pau DAlho,SP
376827,17970,Sao Joao Do Pau DAlho,SP
376905,17970,Sao Joao Do Pau DAlho,SP
376937,17970,Sao Joao Do Pau DAlho,SP
377022,17970,Sao Joao Do Pau DAlho,SP
377073,17970,Sao Joao Do Pau DAlho,SP
377082,17970,Sao Joao Do Pau DAlho,SP
377092,17970,Sao Joao Do Pau Dalho,SP
377138,17970,Sao Joao Do Pau DAlho,SP
377186,17970,Sao Joao Do Pau Dalho,SP
377210,17970,Sao Joao Do Pau DAposBalho,SP
377306,17970,Sao Joao Do Pau DAlho,SP
377324,17970,Sao Joao Do Pau DAlho,SP
377331,17970,Sao Joao Do Pau DAlho,SP
377496,17970,Sao Joao Do Pau DAlho,SP

In [281]:
geo.duplicated().sum()

np.int64(718397)

In [282]:
geo.drop_duplicates(inplace=True)

In [283]:
geo["geolocation_city"].nunique()

5962

In [284]:
# PERFORMING THE SAME STEPS FOR CUSTOMER TABLE CITY COLUMN
customers["customer_city"]= customers["customer_city"].apply(lambda x: unidecode(x))
customers["customer_city"]= customers["customer_city"].apply(keep_only_text)

In [285]:
customers.duplicated().sum()

np.int64(0)

In [286]:
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00012a2ce6f8dcda20d059ce98491703,248ffe10d632bebe4f7267f1f44844c9,6273,Osasco,SP
1,000161a058600d5901f007fab4c27140,b0015e09bb4b6e47c52844fab5fb6638,35550,Itapecerica,MG
2,0001fd6190edaaf884bcaf3d49edf079,94b11d37cd61cb2994a194d11f89682b,29830,Nova Venecia,ES
3,0002414f95344307404f0ace7a26f1d5,4893ad4ea28b2c5b3ddf4e82e79db9e6,39664,Mendonca,MG
4,000379cdec625522490c315e70c7a9fb,0b83f73b19c2019e182fd552c048a22c,4841,Sao Paulo,SP
...,...,...,...,...,...
99436,fffecc9f79fd8c764f843e9951b11341,e5794df8573fa179a90a7b797fc4b71f,95630,Parobe,RS
99437,fffeda5b6d849fbd39689bb92087f431,afbb5a642107cf6bb1ca68e863175f03,22461,Rio De Janeiro,RJ
99438,ffff42319e9b2d713724ae527742af25,680213db6ebd9e4f24d03280cbe10346,6754,Taboao Da Serra,SP
99439,ffffa3172527f765de70084a7e53aae8,48fd7dec70f2b104a1d5e8c5c639102b,37130,Alfenas,MG
99440,ffffe8b65bbe3087b653a978c870db99,736e6bfa0510aa5b878881a226a5fd89,6172,Osasco,SP

In [287]:
query ="select * from olist_products_dataset"
products= pd.read_sql(query, conn)

C:\Users\Manchala Govardhan\AppData\Local\Temp\ipykernel_14452\3138657782.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  products= pd.read_sql(query, conn)

In [288]:
products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225,16,10,14
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000,30,18,20
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154,18,9,15
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371,26,4,26
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625,20,17,13
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300,40,40,40
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700,16,19,16
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400,27,7,27
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700,31,13,20
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083,12,2,7

In [289]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [290]:
products.drop(columns=['product_name_lenght',
       'product_description_lenght', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'], inplace=True)

In [291]:
products

,product_id,product_category_name,product_photos_qty
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,1.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,1.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,1.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,1.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,4.0
...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,2.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,1.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,1.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,2.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,1.0

In [292]:
products["product_category_name"].unique()

array(['perfumaria', 'artes', 'esporte_lazer', 'bebes',
       'utilidades_domesticas', 'instrumentos_musicais', 'cool_stuff',
       'moveis_decoracao', 'eletrodomesticos', 'brinquedos',
       'cama_mesa_banho', 'construcao_ferramentas_seguranca',
       'informatica_acessorios', 'beleza_saude', 'malas_acessorios',
       'ferramentas_jardim', 'moveis_escritorio', 'automotivo',
       'eletronicos', 'fashion_calcados', 'telefonia', 'papelaria',
       'fashion_bolsas_e_acessorios', 'pcs', 'casa_construcao',
       'relogios_presentes', 'construcao_ferramentas_construcao',
       'pet_shop', 'eletroportateis', 'agro_industria_e_comercio', None,
       'moveis_sala', 'sinalizacao_e_seguranca', 'climatizacao',
       'consoles_games', 'livros_interesse_geral',
       'construcao_ferramentas_ferramentas',
       'fashion_underwear_e_moda_praia', 'fashion_roupa_masculina',
       'moveis_cozinha_area_de_servico_jantar_e_jardim',
       'industria_comercio_e_negocios', 'telefonia_fixa',
       'construcao_ferramentas_iluminacao', 'livros_tecnicos',
       'eletrodomesticos_2', 'artigos_de_festas', 'bebidas',
       'market_place', 'la_cuisine', 'construcao_ferramentas_jardim',
       'fashion_roupa_feminina', 'casa_conforto', 'audio',
       'alimentos_bebidas', 'musica', 'alimentos',
       'tablets_impressao_imagem', 'livros_importados',
       'portateis_casa_forno_e_cafe', 'fashion_esporte',
       'artigos_de_natal', 'fashion_roupa_infanto_juvenil',
       'dvds_blu_ray', 'artes_e_artesanato', 'pc_gamer', 'moveis_quarto',
       'cine_foto', 'fraldas_higiene', 'flores', 'casa_conforto_2',
       'portateis_cozinha_e_preparadores_de_alimentos',
       'seguros_e_servicos', 'moveis_colchao_e_estofado',
       'cds_dvds_musicais'], dtype=object)

In [293]:
query = "select * from  product_category_name_translation"
product_name= pd.read_sql(query, conn)

C:\Users\Manchala Govardhan\AppData\Local\Temp\ipykernel_14452\98160967.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  product_name= pd.read_sql(query, conn)

In [294]:
product_name

                 Product Category    product category in english
0           product_category_name  product_category_name_english
1                    beleza_saude                  health_beauty
2          informatica_acessorios          computers_accessories
3                      automotivo                           auto
4                 cama_mesa_banho                 bed_bath_table
..                            ...                            ...
67                         flores                        flowers
68             artes_e_artesanato          arts_and_craftmanship
69                fraldas_higiene            diapers_and_hygiene
70  fashion_roupa_infanto_juvenil      fashion_childrens_clothes
71             seguros_e_servicos          security_and_services

[72 rows x 2 columns]

In [295]:
product_name.drop(index=0, inplace=True)

In [296]:
product_name

                 Product Category product category in english
1                    beleza_saude               health_beauty
2          informatica_acessorios       computers_accessories
3                      automotivo                        auto
4                 cama_mesa_banho              bed_bath_table
5                moveis_decoracao             furniture_decor
..                            ...                         ...
67                         flores                     flowers
68             artes_e_artesanato       arts_and_craftmanship
69                fraldas_higiene         diapers_and_hygiene
70  fashion_roupa_infanto_juvenil   fashion_childrens_clothes
71             seguros_e_servicos       security_and_services

[71 rows x 2 columns]

In [297]:
print(products["product_category_name"].nunique())
print(product_name["Product Category"].nunique())

73
71

In [298]:
# 71 common in both the table ??
# product - a,b,c,d   --4 
# product_name - a, b, e,f   --4

In [299]:
# lets find the category that is in product table but not in product_name table
product_name[~product_name["Product Category"].isin(products["product_category_name"])]

Empty DataFrame
Columns: [Product Category, product category in english]
Index: []

In [300]:
products[~products["product_category_name"].isin(product_name["Product Category"])]["product_category_name"].unique()

array([None, 'pc_gamer', 'portateis_cozinha_e_preparadores_de_alimentos'],
      dtype=object)

In [301]:

product_name.sort_values(by=["Product Category"])["Product Category"].unique()

array(['agro_industria_e_comercio', 'alimentos', 'alimentos_bebidas',
       'artes', 'artes_e_artesanato', 'artigos_de_festas',
       'artigos_de_natal', 'audio', 'automotivo', 'bebes', 'bebidas',
       'beleza_saude', 'brinquedos', 'cama_mesa_banho', 'casa_conforto',
       'casa_conforto_2', 'casa_construcao', 'cds_dvds_musicais',
       'cine_foto', 'climatizacao', 'consoles_games',
       'construcao_ferramentas_construcao',
       'construcao_ferramentas_ferramentas',
       'construcao_ferramentas_iluminacao',
       'construcao_ferramentas_jardim',
       'construcao_ferramentas_seguranca', 'cool_stuff', 'dvds_blu_ray',
       'eletrodomesticos', 'eletrodomesticos_2', 'eletronicos',
       'eletroportateis', 'esporte_lazer', 'fashion_bolsas_e_acessorios',
       'fashion_calcados', 'fashion_esporte', 'fashion_roupa_feminina',
       'fashion_roupa_infanto_juvenil', 'fashion_roupa_masculina',
       'fashion_underwear_e_moda_praia', 'ferramentas_jardim', 'flores',
       'fraldas_higiene', 'industria_comercio_e_negocios',
       'informatica_acessorios', 'instrumentos_musicais', 'la_cuisine',
       'livros_importados', 'livros_interesse_geral', 'livros_tecnicos',
       'malas_acessorios', 'market_place', 'moveis_colchao_e_estofado',
       'moveis_cozinha_area_de_servico_jantar_e_jardim',
       'moveis_decoracao', 'moveis_escritorio', 'moveis_quarto',
       'moveis_sala', 'musica', 'papelaria', 'pcs', 'perfumaria',
       'pet_shop', 'portateis_casa_forno_e_cafe', 'relogios_presentes',
       'seguros_e_servicos', 'sinalizacao_e_seguranca',
       'tablets_impressao_imagem', 'telefonia', 'telefonia_fixa',
       'utilidades_domesticas'], dtype=object)

In [302]:
product_name[product_name["Product Category"]=="pcs"]

   Product Category product category in english
54              pcs                   computers

In [303]:
product_name[product_name["Product Category"]=="portateis_casa_forno_e_cafe"]

               Product Category            product category in english
64  portateis_casa_forno_e_cafe  small_appliances_home_oven_and_coffee

In [304]:
products= pd.merge(products, product_name, left_on="product_category_name", right_on="Product Category", how="left")

In [305]:
products

,product_id,product_category_name,product_photos_qty,Product Category,product category in english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,1.0,perfumaria,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,1.0,artes,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,1.0,esporte_lazer,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,1.0,bebes,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,4.0,utilidades_domesticas,housewares
...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,2.0,moveis_decoracao,furniture_decor
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,1.0,construcao_ferramentas_iluminacao,construction_tools_lights
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,1.0,cama_mesa_banho,bed_bath_table
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,2.0,informatica_acessorios,computers_accessories
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,1.0,cama_mesa_banho,bed_bath_table

In [306]:
products[products["product_category_name"]=="portateis_cozinha_e_preparadores_de_alimentos"]

,product_id,product_category_name,product_photos_qty,Product Category,product category in english
5821,6fd83eb3e0799b775e4f946bd66657c0,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,NaN
7325,5d923ead886c44b86845f69e50520c3e,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,NaN
8819,bed164d9d628cf0593003389c535c6e0,portateis_cozinha_e_preparadores_de_alimentos,2.0,NaN,NaN
11039,1220978a08a6b29a202bc015b18250e9,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,NaN
14266,ae62bb0f95af63d64eae5f93dddea8d3,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,NaN
16182,1954739d84629e7323a4295812a3e0ec,portateis_cozinha_e_preparadores_de_alimentos,4.0,NaN,NaN
17800,c7a3f1a7f9eef146cc499368b578b884,portateis_cozinha_e_preparadores_de_alimentos,5.0,NaN,NaN
18610,7afdd65f79f63819ff5bee328843fa37,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,NaN
26890,a4756663d007b0cd1af865754d08d968,portateis_cozinha_e_preparadores_de_alimentos,4.0,NaN,NaN
29919,cb9d764f38ee4d0c00af64d5c388f837,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,NaN

In [307]:
products.loc[products["product_category_name"]=="pc_gamer","product category in english"]="computers"
products.loc[products["product_category_name"]=="portateis_cozinha_e_preparadores_de_alimentos", "product category in english"]="small_appliances_home_oven_and_coffee"

In [308]:
products[products["product_category_name"]=="portateis_cozinha_e_preparadores_de_alimentos"]

,product_id,product_category_name,product_photos_qty,Product Category,product category in english
5821,6fd83eb3e0799b775e4f946bd66657c0,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,small_appliances_home_oven_and_coffee
7325,5d923ead886c44b86845f69e50520c3e,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,small_appliances_home_oven_and_coffee
8819,bed164d9d628cf0593003389c535c6e0,portateis_cozinha_e_preparadores_de_alimentos,2.0,NaN,small_appliances_home_oven_and_coffee
11039,1220978a08a6b29a202bc015b18250e9,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,small_appliances_home_oven_and_coffee
14266,ae62bb0f95af63d64eae5f93dddea8d3,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,small_appliances_home_oven_and_coffee
16182,1954739d84629e7323a4295812a3e0ec,portateis_cozinha_e_preparadores_de_alimentos,4.0,NaN,small_appliances_home_oven_and_coffee
17800,c7a3f1a7f9eef146cc499368b578b884,portateis_cozinha_e_preparadores_de_alimentos,5.0,NaN,small_appliances_home_oven_and_coffee
18610,7afdd65f79f63819ff5bee328843fa37,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,small_appliances_home_oven_and_coffee
26890,a4756663d007b0cd1af865754d08d968,portateis_cozinha_e_preparadores_de_alimentos,4.0,NaN,small_appliances_home_oven_and_coffee
29919,cb9d764f38ee4d0c00af64d5c388f837,portateis_cozinha_e_preparadores_de_alimentos,1.0,NaN,small_appliances_home_oven_and_coffee

In [309]:
products[products["product_category_name"]=="pc_gamer"]

,product_id,product_category_name,product_photos_qty,Product Category,product category in english
1628,0105b5323d24fc655f73052694dbbb3a,pc_gamer,4.0,NaN,computers
7478,6727051471a0fc4a0e7737b57bff2549,pc_gamer,3.0,NaN,computers
16930,dbe520fb381ad695a7e1f2807d20c765,pc_gamer,6.0,NaN,computers

In [312]:
products["product_category_name"]= products["product category in english"]

In [313]:
products

,product_id,product_category_name,product_photos_qty,Product Category,product category in english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,1.0,perfumaria,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,art,1.0,artes,art
2,96bd76ec8810374ed1b65e291975717f,sports_leisure,1.0,esporte_lazer,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,baby,1.0,bebes,baby
4,9dc1a7de274444849c219cff195d0b71,housewares,4.0,utilidades_domesticas,housewares
...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,furniture_decor,2.0,moveis_decoracao,furniture_decor
32947,bf4538d88321d0fd4412a93c974510e6,construction_tools_lights,1.0,construcao_ferramentas_iluminacao,construction_tools_lights
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,bed_bath_table,1.0,cama_mesa_banho,bed_bath_table
32949,83808703fc0706a22e264b9d75f04a2e,computers_accessories,2.0,informatica_acessorios,computers_accessories
32950,106392145fca363410d287a815be6de4,bed_bath_table,1.0,cama_mesa_banho,bed_bath_table

In [315]:
products.drop(columns=["Product Category","product category in english"], inplace=True)

In [316]:
products

,product_id,product_category_name,product_photos_qty
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,1.0
1,3aa071139cb16b67ca9e5dea641aaa2f,art,1.0
2,96bd76ec8810374ed1b65e291975717f,sports_leisure,1.0
3,cef67bcfe19066a932b7673e239eb23d,baby,1.0
4,9dc1a7de274444849c219cff195d0b71,housewares,4.0
...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,furniture_decor,2.0
32947,bf4538d88321d0fd4412a93c974510e6,construction_tools_lights,1.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,bed_bath_table,1.0
32949,83808703fc0706a22e264b9d75f04a2e,computers_accessories,2.0
32950,106392145fca363410d287a815be6de4,bed_bath_table,1.0

In [317]:
query=("select * from olist_sellers_dataset")
seller = pd.read_sql(query, conn)

C:\Users\Manchala Govardhan\AppData\Local\Temp\ipykernel_14452\1824706530.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  seller = pd.read_sql(query, conn)

In [ ]:
seller

In [ ]:
seller["seller_city"]= seller["seller_city"].str.title()

In [ ]:
seller.duplicated().sum()

In [ ]:
seller[seller["seller_id"].duplicated()]

In [ ]:
seller["seller_city"]= seller["seller_city"].apply(keep_only_text)

In [ ]:
seller

In [ ]:
query="select * from olist_orders_dataset"
orders= pd.read_sql(query, conn)

In [ ]:
orders

In [ ]:
orders["order_status"].unique()

In [ ]:
df= orders.copy()

In [ ]:
orders.info()

In [ ]:
orders= orders[
((orders["order_approved_at"]- orders["order_purchase_timestamp"]).dt.total_seconds()/86400>=0) &
((orders['order_delivered_carrier_date'] - orders['order_approved_at']).dt.days >= 0)
]

In [ ]:
orders

In [ ]:
orders["order_status"].unique()

In [ ]:
orders

In [ ]:
orders[(orders["order_status"]=="canceled")& (orders["order_delivered_customer_date"].notna())]

In [ ]:
to_remove= orders[(orders["order_status"]=="canceled")& (orders["order_delivered_customer_date"].notna())].index

In [ ]:
orders = orders.drop(to_remove)

In [ ]:
orders

In [ ]:
orders.duplicated().sum()

In [ ]:
orders["order_status"].unique()

In [ ]:
query = "select * from olist_order_payments_dataset"
payments= pd.read_sql(query, conn)

In [ ]:
payments.sort_values(by ="payment_sequential", ascending=False)

In [ ]:
payments[payments["order_id"]=="fa65dad1b0e818e3ccc5cb0e39231352"]

In [ ]:
payments[payments["order_id"]=="b81ef226f3fe1789b1e8b2acac839d17"]

In [ ]:
payments.drop(columns=["payment_sequential","payment_installments"], inplace=True)

In [ ]:
payments

In [ ]:
payments[payments["order_id"]=="fa65dad1b0e818e3ccc5cb0e39231352"]

In [ ]:
payments= payments.groupby(["order_id","payment_type"]).sum("payment_value").reset_index()

In [ ]:
payments[payments["order_id"]=="fa65dad1b0e818e3ccc5cb0e39231352"]

In [ ]:
payments.shape

In [ ]:
103886 -101686

In [ ]:
payments.head()

In [ ]:
orders.head()

In [ ]:
print(orders["order_id"].nunique())
print(payments["order_id"].nunique())

In [ ]:
99440-96279

In [ ]:
# orders - cancelled -- payments id --- payment 
# orders - rows cleaned -- payemnts_id -- payment 
# orders -- payment
# payment -- orders

In [ ]:
len(orders[orders["order_status"]=="canceled"])

In [ ]:
orders[~orders["order_id"].isin(payments["order_id"])]

In [ ]:
payments[~payments["order_id"].isin(orders["order_id"])]["order_id"].nunique()

In [ ]:
#orders -- cleaned
# df --- uncleaned

In [ ]:
# df- 1000
# orders- 890
# cleaning - 110 order id

In [ ]:
df[~df["order_id"].isin(orders["order_id"])]

In [ ]:
# df---- orders    --- 3162 orders id

In [ ]:
payments , orders

In [ ]:
orders= pd.merge(orders, payments, on="order_id", how="inner")

In [ ]:
orders["order_id"].nunique()

In [ ]:
orders

In [ ]:
query ="select * from olist_order_items_dataset"
olist_items= pd.read_sql(query, conn)

In [ ]:
olist_items

In [ ]:
print(orders['order_id'].nunique())
print(olist_items['order_id'].nunique())

In [ ]:
#merge -- inner join

In [ ]:
orders= pd.merge(orders, olist_items, on="order_id", how="inner")

In [ ]:
orders

In [ ]:
orders

In [ ]:
orders= orders[(orders["shipping_limit_date"]>orders["order_purchase_timestamp"]) &
(orders["shipping_limit_date"]>orders["order_approved_at"])&
(orders["shipping_limit_date"]<orders["order_delivered_customer_date"])]

In [ ]:
orders.sort_values(by=["order_item_id","order_id"], ascending=False)

In [ ]:
orders[orders["order_id"]=="8272b63d03f5f79c56e9e4120aec44ef"]

In [ ]:
sum(orders[orders["order_id"]=="8272b63d03f5f79c56e9e4120aec44ef"]["price"]+orders[orders["order_id"]=="8272b63d03f5f79c56e9e4120aec44ef"]["freight_value"])

In [ ]:
orders[orders["order_id"]=="ab14fdcfbe524636d65ee38360e22ce8"]

In [ ]:
sum(orders[orders["order_id"]=="ab14fdcfbe524636d65ee38360e22ce8"]["price"]+orders[orders["order_id"]=="ab14fdcfbe524636d65ee38360e22ce8"]["freight_value"])

In [ ]:
orders.drop(columns="order_item_id", inplace=True)

In [ ]:
orders.columns

In [ ]:
orders= orders.groupby(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'payment_type', 'payment_value', 'product_id', 'seller_id',
       'shipping_limit_date']).agg(price=("price", "sum"),
                                   freight_value=("freight_value", "sum"),
                                   Quantity=("product_id","count")).reset_index()

In [ ]:
orders.sort_values(by="Quantity", ascending=False)

In [ ]:
orders[orders["order_id"]=="ab14fdcfbe524636d65ee38360e22ce8"]

In [ ]:
orders[orders["order_id"]=="8272b63d03f5f79c56e9e4120aec44ef"]

In [ ]:
orders.shape

In [ ]:
orders

In [ ]:
pd.merge(orders, customers, left_on="customer_id", right_on="customer_id",how="inner")

In [ ]:
customers.drop(columns="customer_unique_id", inplace=True)

In [ ]:
customers